default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: guest

development:
  <<: *default
  database: boats_development

test:
  <<: *default
  database: boats_test

production:
  <<: *default
  database: boats_production
